set -g default-command "${SHELL}"
set -g default-terminal "tmux-256color"
set -g terminal-features "xterm*:clipboard:ccolour:cstyle:focus:title:RGB,screen*:title,rxvt*:ignorefkeys"
set -sg escape-time 0
set -g focus-events on

# Change prefix to Ctrl+a (much easier on Mac)
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# Switch panes using Option + Vim directions (no prefix needed)
bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R

# Move seamlessly between tmux panes and Neovim splits
is_vim="ps -o state= -o comm= -t '#{pane_tty}' | rg -iq '^[^TXZ ]+ +(.*/)?g?(view|n?vim?x?)(diff)?$'"
bind-key -n C-h if-shell "$is_vim" "send-keys C-h" "select-pane -L"
bind-key -n C-j if-shell "$is_vim" "send-keys C-j" "select-pane -D"
bind-key -n C-k if-shell "$is_vim" "send-keys C-k" "select-pane -U"
bind-key -n C-l if-shell "$is_vim" "send-keys C-l" "select-pane -R"

# Keep terminal behavior clean on Mac
set -g default-command "${SHELL}"
set -g mouse on
# Split panes using | and -
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

# Press prefix + P to instantly launch your 3-pane layout
bind P split-window -h \; split-window -v \; select-pane -t 0 \; send-keys 'nvim' C-m

# ====================================================================
# Plugins (TPM)
# ====================================================================
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'

# Save:  Ctrl-a then Ctrl-s
# Restore: Ctrl-a then Ctrl-r
run '~/.tmux/plugins/tpm/tpm'
